# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from pitakuru/peoples.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import pitakuru.msg

class peoples(genpy.Message):
  _md5sum = "ac59fff88e12974eb0b8f05308bead2c"
  _type = "pitakuru/peoples"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """pitakuru/people_box[] people

================================================================================
MSG: pitakuru/people_box
int16 xmin
int16 ymin
int16 xmax
int16 ymax
int16 id
int16 area
"""
  __slots__ = ['people']
  _slot_types = ['pitakuru/people_box[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       people

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(peoples, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.people is None:
        self.people = []
    else:
      self.people = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.people)
      buff.write(_struct_I.pack(length))
      for val1 in self.people:
        _x = val1
        buff.write(_get_struct_6h().pack(_x.xmin, _x.ymin, _x.xmax, _x.ymax, _x.id, _x.area))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.people is None:
        self.people = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.people = []
      for i in range(0, length):
        val1 = pitakuru.msg.people_box()
        _x = val1
        start = end
        end += 12
        (_x.xmin, _x.ymin, _x.xmax, _x.ymax, _x.id, _x.area,) = _get_struct_6h().unpack(str[start:end])
        self.people.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.people)
      buff.write(_struct_I.pack(length))
      for val1 in self.people:
        _x = val1
        buff.write(_get_struct_6h().pack(_x.xmin, _x.ymin, _x.xmax, _x.ymax, _x.id, _x.area))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.people is None:
        self.people = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.people = []
      for i in range(0, length):
        val1 = pitakuru.msg.people_box()
        _x = val1
        start = end
        end += 12
        (_x.xmin, _x.ymin, _x.xmax, _x.ymax, _x.id, _x.area,) = _get_struct_6h().unpack(str[start:end])
        self.people.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6h = None
def _get_struct_6h():
    global _struct_6h
    if _struct_6h is None:
        _struct_6h = struct.Struct("<6h")
    return _struct_6h
