local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  track_unknown_space: false
  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5  

  static_map: false  
  rolling_window: true
  width: 8
  height: 8
  resolution: 0.05
  plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
  
