# 非常停止/衝突警告
ignore:
  distance: 0.1  # ターゲットからいくらまでの近傍の障害物を無視するか [m]
  angle_min: -45 # 前方を0度として、半時計回りに何度からのデータのみ認識するか [deg]
  angle_max: 45 # 前方を0度として、半時計回りに何度までのデータのみ認識するか [deg]
warning:
  distance: 2.0 # これより近くに障害物があった場合、警告を出します [m]
danger:
  distance: 0.5 # これより近くに障害物があった場合、危険と判断して停止します [m]