(cl:in-package pitakuru-msg)
(cl:export '(STATE-VAL
          STATE
          STATE_KARUGAMO-VAL
          STATE_KARUGAMO
          STATE_COLLISION-VAL
          STATE_COLLISION
          STATE_DANGER-VAL
          STATE_DANGER
          STATE_COSTMAP-VAL
          STATE_COSTMAP
          STATE_MANUAL-VAL
          STATE_MANUAL
          STATE_SCAN-VAL
          STATE_SCAN
          STATE_LOAD-VAL
          STATE_LOAD
          STATE_SHELF-VAL
          STATE_SHELF
          STATE_NAVIGATION-VAL
          STATE_NAVIGATION
          COSTMAP-VAL
          COSTMAP
          SIDE_JOYSTICK-VAL
          SIDE_JOYSTICK
          CTRL_FRONT-VAL
          CTRL_FRONT
          CTRL_SIDE-VAL
          CTRL_SIDE
          TRACKEDS-VAL
          TRACKEDS
))