; Auto-generated. Do not edit!


(cl:in-package pitakuru-msg)


;//! \htmlinclude SoundResult.msg.html

(cl:defclass <SoundResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass SoundResult (<SoundResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SoundResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SoundResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pitakuru-msg:<SoundResult> is deprecated: use pitakuru-msg:SoundResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SoundResult>) ostream)
  "Serializes a message object of type '<SoundResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SoundResult>) istream)
  "Deserializes a message object of type '<SoundResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SoundResult>)))
  "Returns string type for a message object of type '<SoundResult>"
  "pitakuru/SoundResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SoundResult)))
  "Returns string type for a message object of type 'SoundResult"
  "pitakuru/SoundResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SoundResult>)))
  "Returns md5sum for a message object of type '<SoundResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SoundResult)))
  "Returns md5sum for a message object of type 'SoundResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SoundResult>)))
  "Returns full string definition for message of type '<SoundResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SoundResult)))
  "Returns full string definition for message of type 'SoundResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SoundResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SoundResult>))
  "Converts a ROS message object to a list"
  (cl:list 'SoundResult
))
