; Auto-generated. Do not edit!


(cl:in-package pitakuru-msg)


;//! \htmlinclude SoundGoal.msg.html

(cl:defclass <SoundGoal> (roslisp-msg-protocol:ros-message)
  ((type
    :reader type
    :initarg :type
    :type cl:string
    :initform ""))
)

(cl:defclass SoundGoal (<SoundGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SoundGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SoundGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pitakuru-msg:<SoundGoal> is deprecated: use pitakuru-msg:SoundGoal instead.")))

(cl:ensure-generic-function 'type-val :lambda-list '(m))
(cl:defmethod type-val ((m <SoundGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pitakuru-msg:type-val is deprecated.  Use pitakuru-msg:type instead.")
  (type m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<SoundGoal>)))
    "Constants for message type '<SoundGoal>"
  '((:TYPE_ACTIVE . "active")
    (:TYPE_ERROR . "error")
    (:TYPE_WARNING . "warning"))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'SoundGoal)))
    "Constants for message type 'SoundGoal"
  '((:TYPE_ACTIVE . "active")
    (:TYPE_ERROR . "error")
    (:TYPE_WARNING . "warning"))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SoundGoal>) ostream)
  "Serializes a message object of type '<SoundGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'type))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'type))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SoundGoal>) istream)
  "Deserializes a message object of type '<SoundGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'type) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'type) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SoundGoal>)))
  "Returns string type for a message object of type '<SoundGoal>"
  "pitakuru/SoundGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SoundGoal)))
  "Returns string type for a message object of type 'SoundGoal"
  "pitakuru/SoundGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SoundGoal>)))
  "Returns md5sum for a message object of type '<SoundGoal>"
  "45fee44dd4ceb09077e426ff86232920")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SoundGoal)))
  "Returns md5sum for a message object of type 'SoundGoal"
  "45fee44dd4ceb09077e426ff86232920")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SoundGoal>)))
  "Returns full string definition for message of type '<SoundGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string TYPE_ACTIVE = \"active\"~%string TYPE_ERROR = \"error\"~%string TYPE_WARNING = \"warning\"~%~%string type~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SoundGoal)))
  "Returns full string definition for message of type 'SoundGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string TYPE_ACTIVE = \"active\"~%string TYPE_ERROR = \"error\"~%string TYPE_WARNING = \"warning\"~%~%string type~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SoundGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'type))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SoundGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SoundGoal
    (cl:cons ':type (type msg))
))
