// Generated by gencpp from file pitakuru/SoundResult.msg
// DO NOT EDIT!


#ifndef PITAKURU_MESSAGE_SOUNDRESULT_H
#define PITAKURU_MESSAGE_SOUNDRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pitakuru
{
template <class ContainerAllocator>
struct SoundResult_
{
  typedef SoundResult_<ContainerAllocator> Type;

  SoundResult_()
    {
    }
  SoundResult_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::pitakuru::SoundResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pitakuru::SoundResult_<ContainerAllocator> const> ConstPtr;

}; // struct SoundResult_

typedef ::pitakuru::SoundResult_<std::allocator<void> > SoundResult;

typedef boost::shared_ptr< ::pitakuru::SoundResult > SoundResultPtr;
typedef boost::shared_ptr< ::pitakuru::SoundResult const> SoundResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pitakuru::SoundResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pitakuru::SoundResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace pitakuru

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pitakuru::SoundResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pitakuru::SoundResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pitakuru::SoundResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pitakuru::SoundResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pitakuru::SoundResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pitakuru::SoundResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pitakuru::SoundResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::pitakuru::SoundResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::pitakuru::SoundResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pitakuru/SoundResult";
  }

  static const char* value(const ::pitakuru::SoundResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pitakuru::SoundResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
;
  }

  static const char* value(const ::pitakuru::SoundResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pitakuru::SoundResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SoundResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pitakuru::SoundResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::pitakuru::SoundResult_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PITAKURU_MESSAGE_SOUNDRESULT_H
