TrajectoryPlannerROS:
  max_vel_x: 6.0 #2.0
  min_vel_x: 2.5 #0.5
  max_vel_theta: 1.9 #1.0
  min_in_place_vel_theta: 0.9
  acc_lim_theta: 3.2 #3.2
  acc_lim_x: 14.0 #2.5
  acc_lim_y: 14.0 #2.5
  holonomic_robot: false
  meter_scoring: false
  controller_frequency: 30.0
  # ゴール精度
  xy_goal_tolerance: 0.5
  dwa: false
