obstacle_range: 0.5
raytrace_range: 1.0
footprint: [[-0.02, -0.012], [-0.02, 0.012], [0.005, 0.12], [0.005, -0.012]]
#robot_radius: ir_of_robot
inflation_radius: 0.055
 
observation_sources: laser_scan_sensor
 
laser_scan_sensor: 
  #sensor_frame: dtw_robot1/front_laser_link
  #topic: /dtw_robot1/front_laser/scan
  data_type: LaserScan
  marking: true
  clearing: true