local_costmap:
  global_frame: /odom
  robot_base_frame: /base_link
  update_frequency: 5.0 #2.0
  publish_frequency: 4.0 #1.0
  static_map: false
  rolling_window: true
  width: 7.0 #6.0
  height: 7.0 #6.0
  resolution: 0.05
