local_costmap:
  global_frame: odom
  robot_base_frame: base_link

  update_frequency: 30.0
  publish_frequency: 30.0
  transform_tolerance: 0.5  

  static_map: false  
  rolling_window: true
  width: 9.0 #3
  height: 9.0 #3
  resolution: 0.15
  
