controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 3.0
planner_frequency: 0.0
shutdown_costmaps: false
oscillation_timeout: 10.0
oscillation_distance: 0.2
clearing_rotation_allowed: false
