shutdown_costmaps: false
controller_frequency: 30.0
planner_patience: 6.0
controller_patience: 15.0
conservative_reset_dist: 3.0
planner_frequency: 6.0
oscillation_timeout: 10.0
oscillation_distance: 0.2

recovery_behavior_enabled: false
clearing_rotation_allowed: false

recovery_behaviors: conservative_reset

