image_width: 800
image_height: 600
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [ 398.363338,    0.     ,  428.397218,
            0.     ,  397.695608,  363.214093,
            0.     ,    0.     ,    1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.021658, -0.023560, 0.006852, 0.004110, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 396.723236,    0.     ,  435.590026,    0.     ,
            0.     ,  397.297119,  369.265619,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]



