gravity: 1.0 #0.65     # ターゲットへの引力と、障害物からの斥力の比率 (1なら引力のみ使用) [0.0-1.0]
wait_time: 0.5     # ARUCOマーカー未検出回数をこれ以上上回った場合は停止する [s]
reload_wait: 1.0 # 再接続までの待機時間 [sec]
capture: false # show_graphで表示される検出点をpickleに保存するログモード