# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from control_xy/StateWheels.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class StateWheels(genpy.Message):
  _md5sum = "fe7d42a99505b18a4db3afda942ff08d"
  _type = "control_xy/StateWheels"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 left_vel
float32 right_vel
float32 left_current
float32 right_current
time time_stamp


"""
  __slots__ = ['left_vel','right_vel','left_current','right_current','time_stamp']
  _slot_types = ['float32','float32','float32','float32','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left_vel,right_vel,left_current,right_current,time_stamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(StateWheels, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.left_vel is None:
        self.left_vel = 0.
      if self.right_vel is None:
        self.right_vel = 0.
      if self.left_current is None:
        self.left_current = 0.
      if self.right_current is None:
        self.right_current = 0.
      if self.time_stamp is None:
        self.time_stamp = genpy.Time()
    else:
      self.left_vel = 0.
      self.right_vel = 0.
      self.left_current = 0.
      self.right_current = 0.
      self.time_stamp = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f2I().pack(_x.left_vel, _x.right_vel, _x.left_current, _x.right_current, _x.time_stamp.secs, _x.time_stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.time_stamp is None:
        self.time_stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.left_vel, _x.right_vel, _x.left_current, _x.right_current, _x.time_stamp.secs, _x.time_stamp.nsecs,) = _get_struct_4f2I().unpack(str[start:end])
      self.time_stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f2I().pack(_x.left_vel, _x.right_vel, _x.left_current, _x.right_current, _x.time_stamp.secs, _x.time_stamp.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.time_stamp is None:
        self.time_stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.left_vel, _x.right_vel, _x.left_current, _x.right_current, _x.time_stamp.secs, _x.time_stamp.nsecs,) = _get_struct_4f2I().unpack(str[start:end])
      self.time_stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f2I = None
def _get_struct_4f2I():
    global _struct_4f2I
    if _struct_4f2I is None:
        _struct_4f2I = struct.Struct("<4f2I")
    return _struct_4f2I
