# Publish scans from best pose at a max of 10 Hz
base_frame_id: base_link
odom_model_type: diff #omni
odom_alpha5: 0.1
transform_tolerance: 0.2
gui_publish_rate: 10.0
laser_max_beams: 100 #30
min_particles: 1000 #500
max_particles: 10000
kld_err: 0.05
kld_z: 0.99
odom_alpha1: 0.8 #0.2
odom_alpha2: 0.7 #0.2
# translation std dev, m
odom_alpha3: 0.6 #0.08
odom_alpha4: 0.1 #0.02
laser_z_hit: 0.90 #0.5
laser_z_short: 0.05 #0.1
laser_z_max: 0.05
laser_z_rand: 0.5
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_lambda_short: 0.1
laser_model_type: likelihood_field
laser_likelihood_max_dist: 2.0
update_min_d: 0.1 #0.2  #actualizacion de distancia
update_min_a: 0.2 #0.5 #actualización de ángulo
resample_interval: 2
transform_tolerance: 0.1
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0
initial_pose_x: 0
initial_pose_y: 0
initial_pose_a: 0
use_map_topic: true
