map_update_interval: 0.1
maxUrange: 30.0
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2
linearUpdate: 0.1
angularUpdate: 0.1 
temporalUpdate: 3.0
resampleThreshold: 0.25 #0.5
particles: 80
xmin: -100.0
ymin: -100.0
xmax: 100.0
ymax: 100.0
delta: 0.05
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
minimumScore: 0.0
occ_thresh: 0.6 #0.25 



