map_update_interval: 0.5 #5.0 
maxUrange: 30.0 #16.0
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 2
srr: 0.15 #0.2 #0.1
srt: 0.25 #0.4 #0.2
str: 0.2 #0.5 #0.1
stt: 0.4 #1.0 #0.2
linearUpdate: 0.1 #1.0
angularUpdate: 0.1 #0.5 #0.5
temporalUpdate: 3.0
resampleThreshold: 0.5
particles: 50 #30 #50
xmin: -50.0
ymin: -50.0
xmax: 50.0
ymax: 50.0
delta: 0.05
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
